### ISSUE TITLE
Server ownership

### ISSUE THREAD

**Issue by vilgefortz** [xiaotian1339/xiaotian1339.github.io#1]
Hey, do you own server 143.110.227.50? The one that hosts tcgg.xyz. It seems that it runs some script that performs brute force ssh attacks. Please shut it down if it is yours. And if it is yours then shame on you.

**Comment by xiaotian1339** [comment]
I am very sorry ，I have received an evaluation report from a third party, and he also explained the problem to me.It probably started when I started using a third-party SSH communication tool.I am trying to investigate this problem.And solve it as soon as possible.But I haven't found the way and purpose of his attack yet.



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年02月23日 12:18 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [xiaotian1339/xiaotian1339.github.io] Server ownership (Issue #1) |

Hey, do you own server 143.110.227.50? The one that hosts tcgg.xyz. It seems that it runs some script that performs brute force ssh attacks. Please shut it down if it is yours. And if it is yours then shame on you.

**Comment by xiaotian1339** [comment]
> Hey, do you own server 143.110.227.50? The one that hosts tcgg.xyz. It seems that it runs some script that performs brute force ssh attacks. Please shut it down if it is yours. And if it is yours then shame on you.

I am very sorry, I just re-analyzed the login log of my server and found that my password has been brute force cracked, I have taken some temporary security measures, I will install some necessary security engineering to prevent this kind of thing once again.

**Comment by vilgefortz** [comment]
Awesome that you are handling it! Good luck! I suggest ssh via
private/public keys and disable password auth completely.

śr., 23 lut 2022 o 08:51 xiaotian1339 ***@***.***> napisał(a):

**Comment by xiaotian1339** [comment]
Thanks for your suggestion, I have set it
